export enum REPOSITORY {
  DATABASE = 'DATABASE_REPOSITORY',
  PHOTO = 'PHOTO_REPOSITORY',
  PRODUCT = 'PRODUCT_REPOSITORY',
  CATEGORY = 'CATEGORY_REPOSITORY',
  IMAGE = 'IMAGE_REPOSITORY',
}

export enum COD_EXCEPTION {
  CREATE = 460,
  SHOW = 461,
  INDEX = 462,
  UPDATE = 463,
  DELETE = 464,
}

export enum MIMETYPES {
  JPG = 'jpg',
  JPEG = 'jpeg',
  PNG = 'png',
}
